"""
Django settings for genericfrontend project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sys
from django.urls import reverse_lazy
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

sentry_sdk.init(
    dsn="https://cc42c54189b2416a99f64e8f630660cc@o463434.ingest.sentry.io/5468438",
    integrations=[DjangoIntegration()],
    traces_sample_rate=1.0,

    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'common'))
sys.path.insert(0, os.path.join(BASE_DIR, 'appspecific'))
# sys.path.insert(0, os.path.join(BASE_DIR, 'user'))
# sys.path.insert(0, os.path.join(BASE_DIR, 'tests'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^%bai)avhbd0erp=7&(_o_emwgshw2e+zy6*yg71i=g6zg035-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'common.apiauthentication',
    'common.emailengine',
    'common.location',
    'common.login',
    'common.logout',
    'common.media',
    'common.notifications_new',
    'common.registration',
    'common.sessionmanagement',
    'common.smsengine',
    # 'common.paymentgateways',
    'common.supportcentre',
    'corsheaders',
 ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'genericfrontend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                "sekizai.context_processors.sekizai",
            ],
        },
    },
]

WSGI_APPLICATION = 'genericfrontend.wsgi.application'
# WSGI_APPLICATION = 'channel_tut.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'apiautomationdb',
#         'USER': 'apiautomationdb',
#         'PASSWORD': 'Cf9zFy61VTwzWAHWXL4o',
#         'HOST': 'apiautomation-dbi.co1bdjlevwzl.ap-south-1.rds.amazonaws.com',
#         'PORT': '5432',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# AWS S3 bucket,cloudfront setup


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# AWS S3 bucket,cloudfront setup
AWS_S3_CALLING_FORMAT = 'boto.s3.connection.OrdinaryCallingFormat'
AWS_ACCESS_KEY_ID = 'AKIAJFPSNFVE4PGGQTCQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_ARN = 'arn:aws:sns:us-east-1:232459418842:snstesting'
AWS_REGION = "us-east-1"
AWS_STORAGE_BUCKET_NAME = 'akstage-media'
CLOUDFRONT_DOMAIN = "d14qfvm28ubfpo.cloudfront.net"
CLOUDFRONT_ID = "EK6F4GRE09B1Q"

# to make sure the url that the files are served from this domain
AWS_S3_CUSTOM_DOMAIN = CLOUDFRONT_DOMAIN
AWS_DEFAUlT_ACL = None
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
# For Local disable below part
# AWS_LOCATION = 'static'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_REGION)
AWS_PUBLIC_MEDIA_LOCATION = 'static/media/user_media'
DEFAULT_FILE_STORAGE = 'common.utilities.file_storage.PublicMediaStorage'
AWS_PRE_MEDIA_LOCATION = 'static/media/skill_images'
AWS_PRIVATE_MEDIA_LOCATION = 'static/files'
PRIVATE_FILE_STORAGE = 'includes.s3_storage.PrivateMediaStorage'
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880


USER_DEFINED_MEDIA_URL = 'https://d14qfvm28ubfpo.cloudfront.net/static/media/user_media/'
PREDEFINED_MEDIA_URL = 'https://d14qfvm28ubfpo.cloudfront.net/static/media/skill_images/'

# WIKI Controls
SITE_ID = 1
WIKI_ACCOUNT_HANDLING = True
WIKI_ACCOUNT_SIGNUP_ALLOWED = True
LOGIN_REDIRECT_URL = reverse_lazy('wiki:get', kwargs={'path': ''})
ASGI_APPLICATION = 'genericfrontend.routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}