from common.utilities.procedures.procdefinitionvariables.procdefinitionvariables_collection import *
from user.utilities.procedures.procdefinitionvariables.procdefinitionvariables_collection import *
from gymmanagement.utilities.procedures.procdefinitionvariables.procdefinitionvariables_collection import *
from multimedia.utilities.procedures.procdefinitionvariables.procdefinitionvariables_collection import *